version: '3'

vars:
  ROOT_DIR: '.'
  OGEN_VERSION: 'v1.14.0'
  BIN_DIR: '{{.ROOT_DIR}}/bin'
  OGEN: 'ogen'

  OPENAPI_FILE: '{{.ROOT_DIR}}/shared/api/order/v1/order.openapi.yaml'
  TARGET_DIR: '{{.ROOT_DIR}}/shared/pkg/openapi/order/v1'
  PACKAGE_NAME: 'order_v1'

tasks:
  install_ogen:
    desc: "Установить ogen, если не установлен"
    cmds:
      - 'test -f {{.OGEN}} || go install github.com/ogen-go/ogen/cmd/ogen@{{.OGEN_VERSION}}'
    silent: true

  generate:
    desc: "Генерируем Go-код из OpenAPI с помощью ogen"
    deps: [install_ogen]
    cmds:
      - '{{.OGEN}} --target ''{{.TARGET_DIR}}'' --package ''{{.PACKAGE_NAME}}'' --clean --config ogen.config.yaml ''{{.OPENAPI_FILE}}'''


  default:
    desc: "Устанавливаем ogen и генерируем"
    deps: [generate]
