// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: inventory/v1/inventory.proto

// Package inventory.v1 содержит API для предоставления информации о деталях для сборки космических кораблей

package inventory_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Category int32

const (
	// Неизвестно
	Category_UNKNOWN Category = 0
	// Двигатель
	Category_ENGINE Category = 1
	// Топливо
	Category_FUEL Category = 2
	// Иллюминатор
	Category_PORTHOLE Category = 3
	// Крыло
	Category_WING Category = 4
)

// Enum value maps for Category.
var (
	Category_name = map[int32]string{
		0: "UNKNOWN",
		1: "ENGINE",
		2: "FUEL",
		3: "PORTHOLE",
		4: "WING",
	}
	Category_value = map[string]int32{
		"UNKNOWN":  0,
		"ENGINE":   1,
		"FUEL":     2,
		"PORTHOLE": 3,
		"WING":     4,
	}
)

func (x Category) Enum() *Category {
	p := new(Category)
	*p = x
	return p
}

func (x Category) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Category) Descriptor() protoreflect.EnumDescriptor {
	return file_inventory_v1_inventory_proto_enumTypes[0].Descriptor()
}

func (Category) Type() protoreflect.EnumType {
	return &file_inventory_v1_inventory_proto_enumTypes[0]
}

func (x Category) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Category.Descriptor instead.
func (Category) EnumDescriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

type GetPartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPartRequest) Reset() {
	*x = GetPartRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartRequest) ProtoMessage() {}

func (x *GetPartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartRequest.ProtoReflect.Descriptor instead.
func (*GetPartRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *GetPartRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetPartResponce struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PartInformation *PartInformation       `protobuf:"bytes,1,opt,name=partInformation,proto3" json:"partInformation,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetPartResponce) Reset() {
	*x = GetPartResponce{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPartResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartResponce) ProtoMessage() {}

func (x *GetPartResponce) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartResponce.ProtoReflect.Descriptor instead.
func (*GetPartResponce) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *GetPartResponce) GetPartInformation() *PartInformation {
	if x != nil {
		return x.PartInformation
	}
	return nil
}

type PartInformation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Уникальный идентификатор детали
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// Название детали
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Описание детали
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Цена за единицу
	Price float64 `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	// Количество на складе
	StockQuantity *wrapperspb.Int64Value `protobuf:"bytes,5,opt,name=stock_quantity,json=stockQuantity,proto3" json:"stock_quantity,omitempty"`
	// Категория
	Category Category `protobuf:"varint,6,opt,name=category,proto3,enum=inventory.v1.Category" json:"category,omitempty"`
	// Размеры детали
	Dimensions *Dimensions `protobuf:"bytes,7,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	// Информация о производителе
	Manufacturer *Manufacturer `protobuf:"bytes,8,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	// Теги для быстрого поиска
	Tags []string `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	// Гибкие метаданные
	Metadata map[string]*Value `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Дата создания
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Дата обновления
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartInformation) Reset() {
	*x = PartInformation{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartInformation) ProtoMessage() {}

func (x *PartInformation) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartInformation.ProtoReflect.Descriptor instead.
func (*PartInformation) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *PartInformation) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *PartInformation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PartInformation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PartInformation) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PartInformation) GetStockQuantity() *wrapperspb.Int64Value {
	if x != nil {
		return x.StockQuantity
	}
	return nil
}

func (x *PartInformation) GetCategory() Category {
	if x != nil {
		return x.Category
	}
	return Category_UNKNOWN
}

func (x *PartInformation) GetDimensions() *Dimensions {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *PartInformation) GetManufacturer() *Manufacturer {
	if x != nil {
		return x.Manufacturer
	}
	return nil
}

func (x *PartInformation) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *PartInformation) GetMetadata() map[string]*Value {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PartInformation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PartInformation) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Dimensions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Длина
	Length float64 `protobuf:"fixed64,1,opt,name=length,proto3" json:"length,omitempty"`
	// Ширина
	Width float64 `protobuf:"fixed64,2,opt,name=width,proto3" json:"width,omitempty"`
	// Высота
	Height float64 `protobuf:"fixed64,3,opt,name=height,proto3" json:"height,omitempty"`
	// Вес
	Weight        float64 `protobuf:"fixed64,4,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dimensions) Reset() {
	*x = Dimensions{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dimensions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dimensions) ProtoMessage() {}

func (x *Dimensions) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dimensions.ProtoReflect.Descriptor instead.
func (*Dimensions) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *Dimensions) GetLength() float64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Dimensions) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Dimensions) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Dimensions) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type Manufacturer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Название
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Страна производства
	Country string `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	// Сайт производителя
	Website       string `protobuf:"bytes,3,opt,name=website,proto3" json:"website,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manufacturer) Reset() {
	*x = Manufacturer{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manufacturer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manufacturer) ProtoMessage() {}

func (x *Manufacturer) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manufacturer.ProtoReflect.Descriptor instead.
func (*Manufacturer) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *Manufacturer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Manufacturer) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Manufacturer) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The kind of value.
	//
	// Types that are valid to be assigned to Kind:
	//
	//	*Value_StringValue
	//	*Value_Int64Value
	//	*Value_DoubleValue
	//	*Value_BoolValue
	Kind          isValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *Value) GetKind() isValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Value) GetStringValue() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Value) GetInt64Value() int64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_Int64Value); ok {
			return x.Int64Value
		}
	}
	return 0
}

func (x *Value) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *Value) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Kind.(*Value_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

type isValue_Kind interface {
	isValue_Kind()
}

type Value_StringValue struct {
	// Строковое значение
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Value_Int64Value struct {
	// Целое значение
	Int64Value int64 `protobuf:"varint,2,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type Value_DoubleValue struct {
	// Дробное значение
	DoubleValue float64 `protobuf:"fixed64,4,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type Value_BoolValue struct {
	// Логическое значение
	BoolValue bool `protobuf:"varint,5,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*Value_StringValue) isValue_Kind() {}

func (*Value_Int64Value) isValue_Kind() {}

func (*Value_DoubleValue) isValue_Kind() {}

func (*Value_BoolValue) isValue_Kind() {}

var File_inventory_v1_inventory_proto protoreflect.FileDescriptor

const file_inventory_v1_inventory_proto_rawDesc = "" +
	"\n" +
	"\x1cinventory/v1/inventory.proto\x12\finventory.v1\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"$\n" +
	"\x0eGetPartRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"Z\n" +
	"\x0fGetPartResponce\x12G\n" +
	"\x0fpartInformation\x18\x01 \x01(\v2\x1d.inventory.v1.PartInformationR\x0fpartInformation\"\x88\x05\n" +
	"\x0fPartInformation\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12B\n" +
	"\x0estock_quantity\x18\x05 \x01(\v2\x1b.google.protobuf.Int64ValueR\rstockQuantity\x122\n" +
	"\bcategory\x18\x06 \x01(\x0e2\x16.inventory.v1.CategoryR\bcategory\x128\n" +
	"\n" +
	"dimensions\x18\a \x01(\v2\x18.inventory.v1.DimensionsR\n" +
	"dimensions\x12>\n" +
	"\fmanufacturer\x18\b \x01(\v2\x1a.inventory.v1.ManufacturerR\fmanufacturer\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\x12G\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2+.inventory.v1.PartInformation.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1aP\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.inventory.v1.ValueR\x05value:\x028\x01\"j\n" +
	"\n" +
	"Dimensions\x12\x16\n" +
	"\x06length\x18\x01 \x01(\x01R\x06length\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x01R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x01R\x06height\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x01R\x06weight\"V\n" +
	"\fManufacturer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acountry\x18\x02 \x01(\tR\acountry\x12\x18\n" +
	"\awebsite\x18\x03 \x01(\tR\awebsite\"\x9d\x01\n" +
	"\x05Value\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12!\n" +
	"\vint64_value\x18\x02 \x01(\x03H\x00R\n" +
	"int64Value\x12#\n" +
	"\fdouble_value\x18\x04 \x01(\x01H\x00R\vdoubleValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x05 \x01(\bH\x00R\tboolValueB\x06\n" +
	"\x04kind*E\n" +
	"\bCategory\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06ENGINE\x10\x01\x12\b\n" +
	"\x04FUEL\x10\x02\x12\f\n" +
	"\bPORTHOLE\x10\x03\x12\b\n" +
	"\x04WING\x10\x042S\n" +
	"\tInventory\x12F\n" +
	"\aGetPart\x12\x1c.inventory.v1.GetPartRequest\x1a\x1d.inventory.v1.GetPartResponceBNZLgithub.com/TerreDHermes/roscosmos/shared/pkg/proto/inventory/v1;inventory_v1b\x06proto3"

var (
	file_inventory_v1_inventory_proto_rawDescOnce sync.Once
	file_inventory_v1_inventory_proto_rawDescData []byte
)

func file_inventory_v1_inventory_proto_rawDescGZIP() []byte {
	file_inventory_v1_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_v1_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_v1_inventory_proto_rawDesc), len(file_inventory_v1_inventory_proto_rawDesc)))
	})
	return file_inventory_v1_inventory_proto_rawDescData
}

var file_inventory_v1_inventory_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_inventory_v1_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_inventory_v1_inventory_proto_goTypes = []any{
	(Category)(0),                 // 0: inventory.v1.Category
	(*GetPartRequest)(nil),        // 1: inventory.v1.GetPartRequest
	(*GetPartResponce)(nil),       // 2: inventory.v1.GetPartResponce
	(*PartInformation)(nil),       // 3: inventory.v1.PartInformation
	(*Dimensions)(nil),            // 4: inventory.v1.Dimensions
	(*Manufacturer)(nil),          // 5: inventory.v1.Manufacturer
	(*Value)(nil),                 // 6: inventory.v1.Value
	nil,                           // 7: inventory.v1.PartInformation.MetadataEntry
	(*wrapperspb.Int64Value)(nil), // 8: google.protobuf.Int64Value
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_inventory_v1_inventory_proto_depIdxs = []int32{
	3,  // 0: inventory.v1.GetPartResponce.partInformation:type_name -> inventory.v1.PartInformation
	8,  // 1: inventory.v1.PartInformation.stock_quantity:type_name -> google.protobuf.Int64Value
	0,  // 2: inventory.v1.PartInformation.category:type_name -> inventory.v1.Category
	4,  // 3: inventory.v1.PartInformation.dimensions:type_name -> inventory.v1.Dimensions
	5,  // 4: inventory.v1.PartInformation.manufacturer:type_name -> inventory.v1.Manufacturer
	7,  // 5: inventory.v1.PartInformation.metadata:type_name -> inventory.v1.PartInformation.MetadataEntry
	9,  // 6: inventory.v1.PartInformation.created_at:type_name -> google.protobuf.Timestamp
	9,  // 7: inventory.v1.PartInformation.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 8: inventory.v1.PartInformation.MetadataEntry.value:type_name -> inventory.v1.Value
	1,  // 9: inventory.v1.Inventory.GetPart:input_type -> inventory.v1.GetPartRequest
	2,  // 10: inventory.v1.Inventory.GetPart:output_type -> inventory.v1.GetPartResponce
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_inventory_v1_inventory_proto_init() }
func file_inventory_v1_inventory_proto_init() {
	if File_inventory_v1_inventory_proto != nil {
		return
	}
	file_inventory_v1_inventory_proto_msgTypes[5].OneofWrappers = []any{
		(*Value_StringValue)(nil),
		(*Value_Int64Value)(nil),
		(*Value_DoubleValue)(nil),
		(*Value_BoolValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_v1_inventory_proto_rawDesc), len(file_inventory_v1_inventory_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_v1_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_v1_inventory_proto_depIdxs,
		EnumInfos:         file_inventory_v1_inventory_proto_enumTypes,
		MessageInfos:      file_inventory_v1_inventory_proto_msgTypes,
	}.Build()
	File_inventory_v1_inventory_proto = out.File
	file_inventory_v1_inventory_proto_goTypes = nil
	file_inventory_v1_inventory_proto_depIdxs = nil
}
