// Code generated by ogen, DO NOT EDIT.
package order_v1

type CreateOrderRes interface {
	createOrderRes()
}

type GetOrderRes interface {
	getOrderRes()
}

type PayCancelRes interface {
	payCancelRes()
}

type PayOrderRes interface {
	payOrderRes()
}
