// Code generated by ogen, DO NOT EDIT.

package order_v1

// GetOrderParams is parameters of GetOrder operation.
type GetOrderParams struct {
	// UUID заказа.
	OrderUUID string
}

// PayCancelParams is parameters of PayCancel operation.
type PayCancelParams struct {
	// UUID заказа.
	OrderUUID string
}

// PayOrderParams is parameters of PayOrder operation.
type PayOrderParams struct {
	// UUID заказа.
	OrderUUID string
}
