// Code generated by ogen, DO NOT EDIT.
package order_v1

type CreateOrderRes interface {
	createOrderRes()
}

type GetOrderRes interface {
	getOrderRes()
}

type OrderCancelRes interface {
	orderCancelRes()
}

type PayOrderRes interface {
	payOrderRes()
}
