// Code generated by ogen, DO NOT EDIT.

package order_v1

// SetFake set fake values.
func (s *BadRequestError) SetFake() {
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *CreateOrderRequest) SetFake() {
	{
		{
			s.UserUUID = "string"
		}
	}
	{
		{
			s.PartUuids = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.PartUuids = append(s.PartUuids, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *CreateOrderResponse) SetFake() {
	{
		{
			s.OrderUUID = "string"
		}
	}
	{
		{
			s.TotalPrice = float32(0)
		}
	}
}

// SetFake set fake values.
func (s *GenericError) SetFake() {
	{
		{
			s.Message.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetOrderResponse) SetFake() {
	{
		{
			s.OrderDto.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *InternalServerError) SetFake() {
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *NotFoundError) SetFake() {
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *OptOrderStatus) SetFake() {
	var elem OrderStatus
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptPaymentMethod) SetFake() {
	var elem PaymentMethod
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptString) SetFake() {
	var elem string
	{
		elem = "string"
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OrderDto) SetFake() {
	{
		{
			s.OrderUUID = "string"
		}
	}
	{
		{
			s.UserUUID = "string"
		}
	}
	{
		{
			s.PartUuids = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.PartUuids = append(s.PartUuids, elem)
			}
		}
	}
	{
		{
			s.TotalPrice = float32(0)
		}
	}
	{
		{
			s.TransactionUUID = "string"
		}
	}
	{
		{
			s.PaymentMethod.SetFake()
		}
	}
	{
		{
			s.Status.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *OrderStatus) SetFake() {
	*s = OrderStatusPENDINGPAYMENT
}

// SetFake set fake values.
func (s *PayOrderRequest) SetFake() {
	{
		{
			s.PaymentMethod = "string"
		}
	}
}

// SetFake set fake values.
func (s *PayOrderResponse) SetFake() {
	{
		{
			s.TransactionUUID = "string"
		}
	}
}

// SetFake set fake values.
func (s *PaymentMethod) SetFake() {
	*s = PaymentMethodCARD
}
