// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"fmt"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"

	"github.com/ogen-go/ogen/validate"

	std "encoding/json"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestBadRequestError_EncodeDecode(t *testing.T) {
	var typ BadRequestError
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 BadRequestError
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestCreateOrderRequest_EncodeDecode(t *testing.T) {
	var typ CreateOrderRequest
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 CreateOrderRequest
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestCreateOrderResponse_EncodeDecode(t *testing.T) {
	var typ CreateOrderResponse
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 CreateOrderResponse
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestGenericError_EncodeDecode(t *testing.T) {
	var typ GenericError
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 GenericError
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestGetOrderResponse_EncodeDecode(t *testing.T) {
	var typ GetOrderResponse
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 GetOrderResponse
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestInternalServerError_EncodeDecode(t *testing.T) {
	var typ InternalServerError
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 InternalServerError
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestNotFoundError_EncodeDecode(t *testing.T) {
	var typ NotFoundError
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 NotFoundError
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestOrderStatus_EncodeDecode(t *testing.T) {
	var typ OrderStatus
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 OrderStatus
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}

func TestOrderStatus_Examples(t *testing.T) {

	for i, tc := range []struct {
		Input string
	}{
		{Input: "\"PAID\""},
	} {
		tc := tc
		t.Run(fmt.Sprintf("Test%d", i+1), func(t *testing.T) {
			var typ OrderStatus

			if err := typ.Decode(jx.DecodeStr(tc.Input)); err != nil {
				if validateErr, ok := errors.Into[*validate.Error](err); ok {
					t.Skipf("Validation error: %v", validateErr)
					return
				}
				require.NoErrorf(t, err, "Input: %s", tc.Input)
			}

			e := jx.Encoder{}
			typ.Encode(&e)
			require.True(t, std.Valid(e.Bytes()), "Encoded: %s", e.Bytes())

			var typ2 OrderStatus
			require.NoError(t, typ2.Decode(jx.DecodeBytes(e.Bytes())))
		})
	}
}
func TestPayOrderRequest_EncodeDecode(t *testing.T) {
	var typ PayOrderRequest
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 PayOrderRequest
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestPayOrderResponse_EncodeDecode(t *testing.T) {
	var typ PayOrderResponse
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 PayOrderResponse
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
func TestPaymentMethod_EncodeDecode(t *testing.T) {
	var typ PaymentMethod
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 PaymentMethod
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}

func TestPaymentMethod_Examples(t *testing.T) {

	for i, tc := range []struct {
		Input string
	}{
		{Input: "\"CARD\""},
	} {
		tc := tc
		t.Run(fmt.Sprintf("Test%d", i+1), func(t *testing.T) {
			var typ PaymentMethod

			if err := typ.Decode(jx.DecodeStr(tc.Input)); err != nil {
				if validateErr, ok := errors.Into[*validate.Error](err); ok {
					t.Skipf("Validation error: %v", validateErr)
					return
				}
				require.NoErrorf(t, err, "Input: %s", tc.Input)
			}

			e := jx.Encoder{}
			typ.Encode(&e)
			require.True(t, std.Valid(e.Bytes()), "Encoded: %s", e.Bytes())

			var typ2 PaymentMethod
			require.NoError(t, typ2.Decode(jx.DecodeBytes(e.Bytes())))
		})
	}
}
